#!/usr/bin/env node
/**
 * Parallelism evidence, generated from the event log.
 *
 * The submission asks for evidence that workstreams ran in parallel. This reads
 * .verbo/events.jsonl - written by lifecycle hooks as the work happened - and
 * reports what is actually in it. Nothing here is authored: if two agents did not
 * overlap, no amount of formatting will make the chart say they did.
 *
 *   node tools/evidence/report.mjs           print the report
 *   node tools/evidence/report.mjs --write   splice it into docs/SYSTEM.md
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('../../', import.meta.url).pathname;
const LOG = join(ROOT, '.verbo/events.jsonl');
const MAP = join(ROOT, '.verbo/workstreams.json');

if (!existsSync(LOG)) {
  console.error('report: no event log. Evidence is captured as work happens; it cannot be reconstructed.');
  process.exit(1);
}

const events = readFileSync(LOG, 'utf8').trim().split('\n').filter(Boolean).map((l) => JSON.parse(l));
const labels = existsSync(MAP) ? JSON.parse(readFileSync(MAP, 'utf8')) : {};
const label = (id) => labels[id] ?? (id ? id.slice(0, 8) : 'orchestrator');
const t = (iso) => Date.parse(iso);
const clock = (iso) => new Date(iso).toISOString().slice(11, 19);
const dur = (ms) => `${Math.floor(ms / 60000)}m ${String(Math.round((ms % 60000) / 1000)).padStart(2, '0')}s`;

// ── Agent spans ──────────────────────────────────────────────────────────────
const spans = [];
const open = new Map();
for (const e of events) {
  if (e.event === 'SubagentStart') open.set(e.agent, e.ts);
  else if (e.event === 'SubagentStop' && open.has(e.agent)) {
    spans.push({ agent: e.agent, start: open.get(e.agent), end: e.ts });
    open.delete(e.agent);
  }
}
spans.sort((a, b) => t(a.start) - t(b.start));

// ── Waves: spans that overlap in wall-clock time ─────────────────────────────
const waves = [];
for (const s of spans) {
  const w = waves.find((w) => t(s.start) < t(w.end));
  if (w) { w.spans.push(s); if (t(s.end) > t(w.end)) w.end = s.end; }
  else waves.push({ start: s.start, end: s.end, spans: [s] });
}

const toolCalls = new Map();
const failures = [];
for (const e of events) {
  if (e.event === 'PreToolUse') toolCalls.set(e.agent ?? null, (toolCalls.get(e.agent ?? null) ?? 0) + 1);
  if (e.event === 'PostToolUseFailure') failures.push(e);
}
const commits = events.filter((e) => e.event === 'Commit');

// ── Render ───────────────────────────────────────────────────────────────────
const out = [];
const W = 56;
out.push('<!-- generated by tools/evidence/report.mjs - do not edit by hand -->');
out.push('');
out.push(`Generated from ${events.length} lifecycle events spanning `
  + `${clock(events[0].ts)}-${clock(events.at(-1).ts)} UTC.`);
out.push('');

for (const [i, w] of waves.entries()) {
  const span = t(w.end) - t(w.start);
  // Every span overlaps every other one only if the latest start precedes the
  // earliest end. That window is the interval in which all of them were live.
  const latestStart = Math.max(...w.spans.map((s) => t(s.start)));
  const earliestEnd = Math.min(...w.spans.map((s) => t(s.end)));
  const allLive = earliestEnd - latestStart;
  const serial = w.spans.reduce((a, s) => a + (t(s.end) - t(s.start)), 0);

  out.push(`### Wave ${i + 1} — ${w.spans.length} workstreams, ${dur(span)} wall clock`);
  out.push('');
  out.push('```');
  for (const s of w.spans) {
    const a = Math.round(((t(s.start) - t(w.start)) / span) * W);
    const b = Math.max(a + 1, Math.round(((t(s.end) - t(w.start)) / span) * W));
    const bar = ' '.repeat(a) + '#'.repeat(b - a) + ' '.repeat(Math.max(0, W - b));
    out.push(`${label(s.agent).padEnd(12)}|${bar}| ${dur(t(s.end) - t(s.start))}`
      + `  ${toolCalls.get(s.agent) ?? 0} calls`);
  }
  out.push(' '.repeat(12) + '+' + '-'.repeat(W) + '+');
  out.push(' '.repeat(13) + clock(w.start) + ' '.repeat(W - 16) + clock(w.end));
  out.push('```');
  out.push('');
  out.push(`All ${w.spans.length} were simultaneously live for **${dur(allLive)}**. `
    + `Serial execution would have taken ${dur(serial)}; it took ${dur(span)}, `
    + `a **${(serial / span).toFixed(2)}x** speedup.`);
  out.push('');
}

const orchestrator = toolCalls.get(null) ?? 0;
const delegated = [...toolCalls].filter(([k]) => k !== null).reduce((a, [, v]) => a + v, 0);
out.push('### Division of work');
out.push('');
out.push('| | Tool calls |');
out.push('|---|---|');
out.push(`| Orchestrator (spec, contracts, review, integration) | ${orchestrator} |`);
out.push(`| Delegated to workstreams | ${delegated} |`);
out.push('');
out.push(`${((delegated / (delegated + orchestrator)) * 100).toFixed(0)}% of tool calls happened `
  + 'inside an isolated workstream context, not in the main thread.');
out.push('');
out.push('### Recorded failures');
out.push('');
out.push(`${failures.length} tool failures and ${commits.length} commits are in the log. `
  + 'Failures are kept because a run with none is a run that was not instrumented.');
out.push('');

const report = out.join('\n');
if (!process.argv.includes('--write')) { console.log(report); process.exit(0); }

const p = join(ROOT, 'docs/SYSTEM.md');
const doc = readFileSync(p, 'utf8');
const [OPEN, CLOSE] = ['<!-- evidence:begin -->', '<!-- evidence:end -->'];
if (!doc.includes(OPEN)) {
  console.error(`report: ${OPEN} marker not found in docs/SYSTEM.md`);
  process.exit(1);
}
const before = doc.slice(0, doc.indexOf(OPEN) + OPEN.length);
const after = doc.slice(doc.indexOf(CLOSE));
writeFileSync(p, `${before}\n\n${report}\n${after}`);
console.log(`report: spliced ${report.split('\n').length} lines into docs/SYSTEM.md`);
